FROM rvv-testenv

RUN apt-get update && \
  apt-get install -y software-properties-common && \
  rm -rf /var/lib/apt/lists/* && \
  add-apt-repository ppa:maveonair/helix-editor && \
  apt-get update && \
  apt-get install -y \
  clangd \
  clang-format \
  python-is-python3 \
  python3-pip \
  pipx \
  python3-venv \
  stow \
  helix && \
  rm -rf /var/lib/apt/lists/*

RUN curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_0.44.1_Linux_x86_64.tar.gz"
RUN tar xf lazygit.tar.gz lazygit
RUN install lazygit /usr/local/bin
RUN rm lazygit*

RUN wget https://github.com/sharkdp/bat/releases/download/v0.24.0/bat_0.24.0_amd64.deb
RUN dpkg -i bat_0.24.0_amd64.deb
RUN rm bat_0.24.0_amd64.deb

WORKDIR /root
RUN git clone https://github.com/sohnryang/dotfiles
WORKDIR ./dotfiles
RUN stow helix
RUN stow bat

ENV TERM=xterm-color
WORKDIR /root
